<?xml version="1.0"?>
<package format="3">
  <name>aux_tools</name>
  <version>1.0.0</version>
  <description>aux_tools</description>

  <maintainer email="test@gmail.com">test</maintainer>
  <license>BSD</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS2 dependencies -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>image_transport</depend>
  <depend>vehicle_msgs</depend>

  <!-- 如果你真的在用 Python 节点，再加这个 -->
  <!-- <depend>rclpy</depend> -->

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
